[package]
name = "core"
version = "0.0.1"
edition = "2024"
rust-version = "1.87.0"

[dependencies]
glwn = { path = "../glwn" }
math = { path = "../math" }
gl = "0.14.0"

[dev-dependencies]
imagine = "0.5.3"
