[package]
name = "editor"
version = "0.0.1"
edition = "2024"
rust-version = "1.87.0"

[dependencies]
core = { path = "../core" }
winit = "0.30.12"
glutin = "0.32.3"
egui = "0.32.1"
egui-winit = "0.32.1"
egui_glow = "0.32.1"
eframe = "0.32.1"