[package]
name = "gl_window_context"
version = "0.0.1"
edition = "2024"
rust-version = "1.87.0"

[dependencies]
glwn = { path = "../glwn" }
winit = "0.30.12"
glutin = "0.32.3"
glutin-winit = "0.5.0"
raw-window-handle = "0.6.2"
